services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news-import-api-app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news-import-api-queue
    entrypoint: ["/usr/local/bin/wait-for-composer.sh"]
    depends_on:
      - app
    volumes:
      - .:/var/www
